<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>GSL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Number</string>
			<key>match</key>
			<string>([0-9]+(.[0-9]+)?)</string>
			<key>name</key>
			<string>constant.numeric.gsl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(")</string>
			<key>comment</key>
			<string>String</string>
			<key>end</key>
			<string>((?&lt;=[^\\])")</string>
			<key>name</key>
			<string>string.quoted.double.gsl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.gsl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(')</string>
			<key>comment</key>
			<string>String</string>
			<key>end</key>
			<string>((?&lt;=[^\\])')</string>
			<key>name</key>
			<string>string.quoted.single.gsl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.gsl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.ruby</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>End-of-line Comment</string>
			<key>end</key>
			<string>\n</string>
			<key>match</key>
			<string>((#)[^\n]*)</string>
			<key>name</key>
			<string>comment.line.gsl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Operator</string>
			<key>match</key>
			<string>(\*|\/|\+|\-|\=|\&lt;|\&gt;|\||\&amp;|\!|\?)</string>
			<key>name</key>
			<string>keyword.operator.gsl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Special Operator</string>
			<key>match</key>
			<string>(\:)</string>
			<key>name</key>
			<string>keyword.operator.special.gsl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Punctuation</string>
			<key>match</key>
			<string>(\.|\(|\))</string>
			<key>name</key>
			<string>punctuation.separator.gsl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Script Keyword</string>
			<key>match</key>
			<string>(\b(after|as|before|by|from|noalias|nostack|to|where)\b)</string>
			<key>name</key>
			<string>keyword.gsl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Script Command Keyword</string>
			<key>match</key>
			<string>(\b(abort|append|close|copy|define|delete|echo|else|elsif|endfor|endfunction|endif|endmacro|endnew|endscope|endtemplate|endwhile|for|function|gsl|if|include|invoke|last|literal|macro|move|new|next|output|return|save|scope|sort|template|while|xml)\b)</string>
			<key>name</key>
			<string>keyword.gsl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(([a-zA-Z_][a-zA-Z_\-0-9]*)\s*(\())</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.gsl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.gsl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Function Call</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.gsl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.functioncall.gsl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.gsl.body</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Identifier</string>
			<key>match</key>
			<string>(\b([a-zA-Z_][a-zA-Z_\-0-9]*)\b)</string>
			<key>name</key>
			<string>entity.other.attribute-name.gsl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.gsl.body</string>
	<key>uuid</key>
	<string>2d2f44c7-4240-481c-8f88-477993e9aab5</string>
</dict>
</plist>
